Run server in background to connect to client

diff --git a/.github/workflows/pull_triggered.yml b/.github/workflows/pull_triggered.yml
--- a/.github/workflows/pull_triggered.yml
+++ b/.github/workflows/pull_triggered.yml
@@ -34,6 +34,8 @@ jobs:
       - name: Run python server.py to see if it works
         run: timeout 5 python3 server.py || ( [[ $? -eq 124 ]] && exit 0 || exit 1 )
       
+      # if errno is 111, then the client failed to connect as is expected, so exit 0
       - name: Run python client.py to see if it works
-        run: timeout 5 python3 client.py || ( [[ $? -eq 124 ]] && exit 0 ) || exit 1
-          
+        run: |
+          timeout 6 python3 server.py & # start server in background for connection
+          timeout 5 python3 client.py || ( [[ $? -eq 111 ]] && exit 0 || exit 1 )
